#!/bin/bash
#
# Verify output on a pre-compiled 32-bit ELF object file

"$ELFREF" "$ROOT/elf32.o" > out 2>&1
[ $? -ne 0 ] && exit 1

# Normalize path names
cat out | sed -E '1 s/\((.*)*\)/(filename)/' > out.filtered

diff out.filtered "$ROOT/elf32.ref" > diffs 2>/dev/null
if [ $? -ne 0 ]; then
	echo "output differs from reference"
	exit 1
fi

exit 0
